spring:
  application:
    name: anime

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  mybatis:
    mapper-locations: classpath:/mappers/**/*.xml
    type-aliases-package: com.anime.domain

jwt:
  secret: ${JWT_SECRET}
  expiration: ${JWT_EXPIRATION}

management:
  endpoints:
    web:
      exposure:
        include: health