spring:
  application:
    name: anime

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/anime_tracker
    username: root
    password: 0000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

jwt:
  secret: 8DK8ClivkVvDjB2IfrrL/Oott651ZbBOwzIRn2qWPB4=
  expiration: 3600000

management:
  endpoints:
    web:
      exposure:
        include: health